---
- name: add mappings to /etc/hosts
  blockinfile:
    path: "{{ HOSTS_FILE }}"
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: "{{ HOST_NAME_INFLUXDB }}", ip: "{{ HOST_IP_INFLUXDB }}" }
    - { name: "{{ HOST_NAME_GRAFANA }}", ip: "{{ HOST_IP_GRAFANA }}" }
    - { name: "{{ HOST_NAME_TELEGRAF }}", ip: "{{ HOST_IP_TELEGRAF }}" }
  tags:
    - update_hosts
