---
- name: install epel
  yum:
    name:
      - epel-release

- name: install packages
  yum:
    name:
      - chrony
      - libselinux-python
      - vim
      - vim-enhanced
      - mc
      - screen
      - ccze
      - redhat-lsb-core
      - wget
      - yum-utils
      - htop
      - sudo
      - iftop
      - net-tools
      - elinks
      - lynx
      - bind-utils
      - deltarpm
      - lsof
      - tree
      - traceroute
      - tcpdump
      - nmap
      - unzip
      - lbzip2
      - fuse-sshfs
      - bash-completion
    state: latest

- name: copy .screenrc to root user
  copy:
    src: screenrc
    dest: /root/.screenrc
    owner: root
    group: root
    mode: '0600'

- name: edit bashrc, vimrc
  shell:
    echo "alias vi='vim'" >> /root/.bashrc && echo "colorscheme desert" >> /etc/vimrc

- name: set timezone
  timezone:
    name: "{{ TIMEZONE_OS }}"

- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: add mappings to /etc/hosts
  blockinfile:
    path: "{{ HOSTS_FILE }}"
    block: |
      {{ item.ip }} {{ item.name }}.{{ FAKE_DOMAIN }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: "{{ HOST_NAME_DCS_01 }}", ip: "{{ HOST_IP_DCS_01 }}" }
    - { name: "{{ HOST_NAME_DCS_02 }}", ip: "{{ HOST_IP_DCS_02 }}" }
    - { name: "{{ HOST_NAME_DCS_03 }}", ip: "{{ HOST_IP_DCS_03 }}" }
    - { name: "{{ HOST_NAME_PG01 }}", ip: "{{ HOST_IP_PG01 }}" }
    - { name: "{{ HOST_NAME_PG02 }}", ip: "{{ HOST_IP_PG02 }}" }
    - { name: "{{ HOST_NAME_PG03 }}", ip: "{{ HOST_IP_PG03 }}" }
    - { name: "{{ HOST_NAME_INFLUXDB }}", ip: "{{ HOST_IP_INFLUXDB }}" }
    - { name: "{{ HOST_NAME_GRAFANA }}", ip: "{{ HOST_IP_GRAFANA }}" }
    - { name: "{{ HOST_NAME_TELEGRAF }}", ip: "{{ HOST_IP_TELEGRAF }}" }
    - { name: "{{ HOST_NAME_ELASTIC_NODE1 }}", ip: "{{ HOST_IP_ELASTIC_NODE1 }}" }
    - { name: "{{ HOST_NAME_ELASTIC_NODE2 }}", ip: "{{ HOST_IP_ELASTIC_NODE2 }}" }
    - { name: "{{ HOST_NAME_ELASTIC_NODE3 }}", ip: "{{ HOST_IP_ELASTIC_NODE3 }}" }
    - { name: "{{ HOST_NAME_KIBANA }}", ip: "{{ HOST_IP_KIBANA }}" }
    - { name: "{{ HOST_NAME_LOGSTASH }}", ip: "{{ HOST_IP_LOGSTASH }}" }
    - { name: "{{ HOST_NAME_ZOO1 }}", ip: "{{ HOST_IP_ZOO1 }}" }
    - { name: "{{ HOST_NAME_ZOO2 }}", ip: "{{ HOST_IP_ZOO2 }}" }
    - { name: "{{ HOST_NAME_ZOO3 }}", ip: "{{ HOST_IP_ZOO3 }}" }
    - { name: "{{ HOST_NAME_KAFKA1 }}", ip: "{{ HOST_IP_KAFKA1 }}" }
    - { name: "{{ HOST_NAME_KAFKA2 }}", ip: "{{ HOST_IP_KAFKA2 }}" }
    - { name: "{{ HOST_NAME_KAFKA3 }}", ip: "{{ HOST_IP_KAFKA3 }}" }
    - { name: "{{ HOST_NAME_SCHEMA_REGISTRY }}", ip: "{{ HOST_IP_SCHEMA_REGISTRY }}" }
    - { name: "{{ HOST_NAME_KAFKA_CONNECT }}", ip: "{{ HOST_IP_KAFKA_CONNECT }}" }
  tags:
    - update_hosts

- name: firewalld disable
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: set locale on database and servers
  shell: |
    localedef -i en_US -f UTF-8 en_US.UTF-8
    localectl set-locale LANG=en_US.UTF-8
